#!/usr/bin/env bash
# Regenerate docs/APPLY-2026-09-10-MIGRATIONS.sql from the migration files.
#
#   ./scripts/build-apply-sql.sh
#
# The operator applies migrations by hand in the Supabase SQL editor — the
# migration ledger is drifted (docs/core_schema_diff.md §3), so `supabase db
# push` is not safe here. Pasting several files in the right order is exactly
# the kind of step that goes wrong at 11pm, so this concatenates them into one
# paste, with a header saying what it does and verification queries at the end.
#
# The output is GENERATED. If a migration changes, run this again rather than
# editing the output; a hand-edited copy that has drifted from the real
# migrations is worse than no copy at all.
#
# This script only writes a file. It applies nothing to any database.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=docs/APPLY-2026-09-10-MIGRATIONS.sql
FILES=(
  supabase/migrations/20260910120000_finalize_link_tolerance_and_lock_order.sql
  supabase/migrations/20260910130000_stripe_checkout_attempts.sql
)

for f in "${FILES[@]}"; do
  [ -f "$f" ] || { echo "missing migration: $f" >&2; exit 1; }
done

{
  cat <<'HEADER'
-- ============================================================================
-- HPS — apply by hand in the Supabase SQL editor.  2026-09-10
-- ============================================================================
-- GENERATED FILE — produced by scripts/build-apply-sql.sh from, in order:
--
--   supabase/migrations/20260910120000_finalize_link_tolerance_and_lock_order.sql
--   supabase/migrations/20260910130000_stripe_checkout_attempts.sql
--
-- Do not edit this file by hand, and do not put it in supabase/migrations/ —
-- it is a convenience for the operator, not a migration.
--
-- WHY BY HAND, NOT `supabase db push`: the migration ledger is drifted
-- (docs/core_schema_diff.md §3), so `db push` may try to replay history that is
-- already present. Paste this whole file into the SQL editor and run it once.
--
-- WHAT IT DOES
--   1. Replaces public.finalize_checkout_payment(jsonb) so that
--      a) a link naming a row that no longer exists (a contact merged away in
--         the admin, say) no longer throws the whole payment away, and
--      b) the registration is locked BEFORE the payment insert, so two
--         payments for one registration cannot deadlock each other.
--      Also revokes append_note_line from PUBLIC/anon/authenticated, which it
--      was granted by default; production currently has that grant.
--   2. Creates public.stripe_checkout_attempts — one row per Checkout Session
--      recording the amount this server authorised, so editing an event's fee
--      cannot invalidate a session a customer was already quoted.
--
-- SAFETY
--   * No existing table is altered. No existing row is read or written.
--   * Safe BEFORE or AFTER deploying the code: old code never touches the new
--     table, and new code treats a missing table or row as "fall back to the
--     previous behaviour".
--   * Safe to run twice (CREATE OR REPLACE / CREATE TABLE IF NOT EXISTS).
--   * It does NOT touch the $80 Community Cup record. That is a separate,
--     scoped step — see docs/STAGE-1-4-1-PRICING-AND-STRIPE-CLOSEOUT.md §14.
--
-- Verification queries are at the bottom of this file.
-- ============================================================================

HEADER

  n=0
  total=${#FILES[@]}
  for f in "${FILES[@]}"; do
    n=$((n + 1))
    printf '\n-- ############################################################################\n'
    printf -- '-- ## %d of %d — %s\n' "$n" "$total" "$(basename "$f")"
    printf -- '-- ############################################################################\n\n'
    cat "$f"
  done

  cat <<'FOOTER'


-- ############################################################################
-- ## Verification — run this after the above and read the row.
-- ############################################################################
-- Every column should come back true EXCEPT the last, which stays 1 until the
-- $80 record is reconciled separately.

select
  to_regclass('public.stripe_checkout_attempts') is not null              as attempts_table_created,
  (select position('v_reg_found' in pg_get_functiondef(p.oid)) > 0
     from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'finalize_checkout_payment') as lock_order_fix_present,
  (select position('no longer exists' in pg_get_functiondef(p.oid)) > 0
     from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'finalize_checkout_payment') as link_tolerance_present,
  (select not bool_or(grantee::text in ('PUBLIC', 'anon', 'authenticated'))
     from information_schema.routine_privileges
    where routine_schema = 'public' and routine_name = 'append_note_line'
      and privilege_type = 'EXECUTE')                                       as append_note_line_locked_down,
  (select relrowsecurity from pg_class
    where oid = 'public.stripe_checkout_attempts'::regclass)                as attempts_rls_enabled,
  (select count(*) from public.registrations
    where id = '803e3697-4476-41ea-bdaa-afec654bdf7c'
      and payment_status = 'pending')                                      as eighty_dollar_still_pending;
FOOTER
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines) from ${#FILES[@]} migrations"
